# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8 (local)
        entry: flake8
        language: system
        types: [ python ]  # ✅ Ensures only .py files are checked
        args: [ "--config=.flake8" ]
