name: AI Chatbot WS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          HOST: 'localhost'
          PORT: '5000'
          MODEL_API: 'Meta-Llama-3-8B-Instruct.Q4_0.gguf'
          MODEL_WS: 'Meta-Llama-3-8B-Instruct.Q4_0.gguf'
        run: |
          pytest --cov=src --cov-fail-under=90